### PR TITLE
set NAWIPS to path holding Gemenviron by default

### PR DESCRIPTION
**Pull request by akrherz**
see #57

### CODE REVIEW

**Comment by akrherz** [comment]
Any bash/csh experts out there?  Please review this PR and chime in with your opinions!

**Comment by mzuranski** [comment]
@akrherz FYI I also opened #80 to isolate this topic from the rest of #57

**Comment by akrherz** [comment]
Yeah @sgdecker, that's a fair question and perhaps I am over-engineering here.  I am worried about symlinks being used, but perhaps that is not justified.

**Comment by sgdecker** [comment]
@akrherz For the record, I dumped the Gemenviron.profile file from this branch into [ShellCheck](https://www.shellcheck.net/), and it found plenty to complain about it, but the specific line in question here was fine. It's probably OK either way.

**Comment by akrherz** [comment]
@sgdecker Thanks, I did not know about shellcheck!  I'll take this PR in a few days unless anybody objects!

**Pull request merged**
