### PR TITLE
Support Level III Super Res

### LINKED ISSUE #72: Support NEXRAD Level III Super-Res
As of this week, "super-res" level III products are now flowing over NWS dissemination systems like NOAAPort.  This issue summaries work done to support these products in GEMPAK.  There are two relevant PNS/SCNs at play here:

- [PNS 21-55](https://www.weather.gov/media/notification/pdf2/pns21-55_reduce_sbn_wsr-88d.pdf) Soliciting Comments on a Change to NEXRAD Product Dissemination via NOAAPORT/SBN on December 1, 2021
- [SCN 21-96](https://www.weather.gov/media/notification/pdf2/scn21-96_sbn_super-res.pdf) Change to NEXRAD Product Dissemination via NOAAPort/SBNon or Around February 2, 2022

My understanding is that NCEP NAWIPS will **not** support these products as they are considered *enhancements* and national centers they support continue to migrate to AWIPS 2.  Having said that, never say never, but the GEMPAK community should try to see what can be done prior to anything "coming from on high".

So the pressing issue at hand here is if/when some of the pre-super-res products that are heavily used, like `N0Q` are removed from noaaport.  The expectation is that these products would still remain on other non-push dissemination systems, but the Unidata community is heavily tied to NOAAPort.  My understanding at the moment is that the products slated to be removed have not yet, due to various NWS national centers yet to migrate off noaaport for level III reception.

# Table 1 RADAR PRODUCTS TO BE REMOVED FROM NOAAPORT/SBN

WMO HEADING | PRODUCT|  DESCRIPTION
--- | --- | --
NXUS6i | GSM | General Status Message 2/GSM
SDUS7i | NET | Echo Tops 4km X 4km 41/ET
SDUS2i | N1S | Storm Relative Velocity .54nm X 1deg 16LVL 56/SRM 1.3-1.5DEG
SDUS2i | N2S | Storm Relative Velocity .54nm X 1deg 16LVL 56/SRM 2.4-2.5DEG
SDUS3i | N3S | Storm Relative Velocity .54nm X 1deg 16LVL 56/SRM 3.1-3.5DEG
SDUS4i | RCM | Radar Coded Message 74/RCM
SDUS4i | RSL | Archive III Status Product 152/ASP
SDUS8i | DOD | Dig. One Hour Difference Accumulation 174/DOD
SDUS8i | DSD | Dig. Storm Total Difference Accumulation 175/DSD
SDUS5i | NXQ | Base Reflectivity .54nm X 1deg 256LVL 94/DR -0.2DEG
SDUS5i | NYQ | Base Reflectivity .54nm X 1deg 256LVL 94/DR 0.0-0.2DEG
SDUS5i | NZQ | Base Reflectivity .54nm X 1deg 256LVL 94/DR 0.3-0.4DEG
SDUS5i | N0Q | Base Reflectivity .54nm X 1deg 256LVL 94/DR 0.5DEG
SDUS5i | NAQ | Base Reflectivity .54nm X 1deg 256LVL 94/DR 0.9DEG
SDUS2i | N1Q | Base Reflectivity .54nm X 1deg 256LVL 94/DR 1.3-1.5DEG
SDUS2i | NBQ | Base Reflectivity .54nm X 1deg 256LVL 94/DR 1.8DEG
SDUS2i | N2Q | Base Reflectivity .54nm X 1deg 256LVL 94/DR 2.4-2.5DEG
SDUS2i | N3Q | Base Reflectivity .54nm X 1deg 256LVL 94/DR 3.1-3.5DEG
SDUS5i | NXU | Base Velocity .13nm X 1deg 256LVL 99/DV -0.2DEG
SDUS5i | NYU | Base Velocity .13nm X 1deg 256LVL 99/DV 0.0-0.2DEG
SDUS5i | NZU | Base Velocity .13nm X 1deg 256LVL 99/DV 0.3-0.4DEG
SDUS5i | N0U | Base Velocity .13nm X 1deg 256LVL 99/DV 0.5DEG
SDUS5i | NAU | Base Velocity .13nm X 1deg 256LVL 99/DV 0.9DEG
SDUS2i | N1U | Base Velocity .13nm X 1deg 256LVL 99/DV 1.3-1.5DEG

# Table 2 RADAR PRODUCTS TO BE ADDED TO NOAAPORT/SBN
WMO HEADING | PRODUCT|  DESCRIPTION
--- | --- | --
SDUS5i | NXB | Base Reflectivity .13nm X .5deg 256LVL 153/SDR -0.2DEG
SDUS5i | NYB | Base Reflectivity .13nm X .5deg 256LVL 153/SDR 0.0-0.2DEG
SDUS5i | NZB | Base Reflectivity .13nm X .5deg 256LVL 153/SDR 0.3-0.4DEG
SDUS5i | N0B | Base Reflectivity .13nm X .5deg 256LVL 153/SDR 0.5DEG
SDUS5i | NAB | Base Reflectivity .13nm X .5deg 256LVL 153/SDR 0.9DEG
SDUS2i | N1B | Base Reflectivity .13nm X .5deg 256LVL 153/SDR 1.3-1.5DEG
SDUS2i | NBB | Base Reflectivity .13nm X 1deg 256LVL 153/SDR 1.8DEG
SDUS2i | N2B | Base Reflectivity .13nm X 1deg 256LVL 153/SDR 2.4-2.5DEG
SDUS2i | N3B | Base Reflectivity .13nm X 1deg 256LVL 153/SDR 3.1-3.5DEG
SDUS5i | NXG | Base Velocity .13nm X .5deg 256LVL 154/SDV -0.2DEG
SDUS5i | NYG | Base Velocity .13nm X .5deg 256LVL 154/SDV 0.0-0.2DEG
SDUS5i | NZG | Base Velocity .13nm X .5deg 256LVL 154/SDV 0.3-0.4DEG
SDUS5i | N0G | Base Velocity .13nm X .5deg 256LVL 154/SDV 0.5DEG 
SDUS5i | NAG | Base Velocity .13nm X .5deg 256LVL 154/SDV 0.9DEG
SDUS2i | N1G | Base Velocity .13nm X .5deg 256LVL 154/SDV 1.3-1.5DEG 

Hopefully we, the GEMPAK Community, can get this resolved quickly :)

### PR DESCRIPTION
**Pull request by akrherz**
refs #72
obsoletes #71

Pull request that implements code/table changes necessary to support NEXRAD Level III super res.  Thanks to @pjpokran for getting this PR off to an excellent start!

### CODE REVIEW

**Comment by akrherz** [comment]
@pjpokran I found your added `upc_n0q.tbl` to be identical to the already bundled `upc_ref2.tbl`.  With ac07fcd, I consolidated this back down.  Is there a reason this was added that I am unaware of?

**Comment by pjpokran** [comment]
@akrherz I didn't realize that table was there. My radar composites are running with an older version of GEMPAK that didn't have that upc_ref2.tbl. If it's identical, that's fine. But you'll have to update the line in gempak/tables/sat/imgtyp.tbl as well, since it's using my file name.

**Comment by akrherz** [comment]
I think I am done tweaking for now, anybody wish to review this? @mzuranski @pjpokran ?

**Comment by mzuranski** [comment]
I'm following along with these changes, trying to adjust my 7.5.1 install, but I'm still seeing IMCBAR frequency ignored.  This image was made with **IMCBAR   = 31/V/CR/.98;.5/.84;.02/-10**  The only other difference I can think of is I'm running Ubuntu but I don't see how that could be related.  Can others verify if IMCBAR frequency works for them or not on 7.14?

test_N0B_gempak

**Comment by akrherz** [comment]
I get the same thing, but I don't think your frequency=-10 is doing what you expect.  `ph IMCBAR` says

>       Frequency describes the levels to be labeled.  If the frequency is positive, the labels are plotted on the right/top of the color bar. If it is negative, the labels are plotted on the left/bottom of the color bar.  The default is -1.

I am looking into this more.

**Comment by akrherz** [comment]
Ah, `gempak/source/gemlib/im/imcbar.f` has special codes to handle this.  Testing a patch now....

**Comment by akrherz** [comment]
Getting close :upside_down_face: 
ss

**Comment by akrherz** [comment]
- Good: N0B, N0G nicely displays now in `nmap2` `gpmap`
- Bad: N0Q does not display nicely :(  I fouled up more tables with the NCEP 7.14.0 merge.  bad daryl!

**Comment by pjpokran** [comment]
Daryl, this all looks good to me. I haven't tested any of your other changes since I'm not using other angles, but on paper they all look good. Thanks for all the additional work on this!

**Comment by akrherz** [comment]
I'm done tinkering with this PR and will follow up with others as I find things to fix :/

**Comment by sebenste** [comment]
Just curious, what command syntax did you use to make that national mosaic?

**Comment by akrherz** [comment]
> Just curious, what command syntax did you use to make that national mosaic?

Just [nex2img](https://docs.unidata.ucar.edu/gempak/man/prog/nex2img.html)

**Comment by pjpokran** [comment]
Gilbert - I'm writing up an email to another explaining how I do the mosiacs - when I'm done I can forward that and the script/etc to you.

**Comment by sebenste** [comment]
> 

Great, thanks!

**Comment by akrherz** [comment]
I don't know of further feedback coming on this and can easily followup with issues folks find with any testing that comes.  I have some more cosmetic things to tweak overtop this PR, so want to get it in now to keep merge nightmares limited.

**Comment by mzuranski** [comment]
@akrherz Since this is going to get closed out soon, how would you feel if I opened a new issue for imcbar frequency?  

[The 7.5.1 documentation](https://docs.unidata.ucar.edu/gempak/man/parm/imcbar.html) states:
> Frequency describes the levels to be labeled.  If the frequency is
     positive, the labels are plotted on the right/top of the color bar.
     If it is negative, the labels are plotted on the left/bottom of the
     color bar.  The default is -1.

...and that's it.

Granted those docs are now obsolete, they're still the best we've got (as far as I'm aware).  While I'm not expecting a change to the behavior anytime soon, I would at least like it noted someplace that the frequency value is ignored for certain products as to avoid confusion.  

I'll also close out #15 as it's old and probably related to this anyway.

**Comment by akrherz** [comment]
> how would you feel if I opened a new issue for imcbar frequency?

Yes please, I was going to do the same, but it slipped my mind yesterday.

**Pull request merged**
