### PR TITLE
add more local NEXRAD to imgtyp.tbl

### PR DESCRIPTION
**Pull request by akrherz**
refs #102

### CODE REVIEW

**Comment by akrherz** [comment]
@sebenste Did I get them all here?

**Comment by sebenste** [comment]
Looks like it! Nice work, Daryl.

**Comment by sebenste** [comment]
From Kevin Polston:

o I was using EAX on NMAP2 and going thru the products. The dual pol stuff looks pretty good. However, unless I did something wrong there are a few issues I’ve seen. First of all…the N0B and N0G (base reflect/velocity) products no longer works. My script shows “no entry in imgtyp.tbl and in NMAP2 it shows I’m still receiving the data but it’s all white. So unless I messed up something, there’s a problem. That also occurs on N1B/N1G and all the other reflect/velocity products for EAX.  For the N0S product (storm relative velocity) I’m getting data but when I click on load in NMAP2 the program bombs. It crashes. The same thing happens for the NMD product as well as NCR (composite reflectivity). The program crashes. For the TDWR data it looks like NMAP2 is saying the refl/vel products are “unsupported data” and is not displaying although the VAD Wind Profile did.  So it seems like Daryl got the dual pol products working but butchered up the regular bad reflectivity and velocity. Unless I copied over something wrong but I don’t think that’s the case

**Comment by mzuranski** [comment]
@sebenste Have him try adding these lines back to imgtyp.tbl

```
LOCAL .25 KM  BASE  REFLECT        0    255      7    153      1 upc_ref2.tbl
LOCAL .25 KM  RADIAL VELOCITY      0    255      7    154      1 upc_vel2.tbl
```

**Comment by akrherz** [comment]
Thanks @mzuranski 

:zero: days since daryl has fouled up a GEMPAK table.

**Comment by mzuranski** [comment]
I'm thinking those two lines should take care of N.B/N.G products, but others may still be missing for some of the other products @sebenste mentioned (N.S, NMD, NCR).  I'd just need to dig deeper to figure out the ID numbers for those, not sure what they are off the top of my head.

**Comment by mzuranski** [comment]
> Yes that took care of the reflectivity and velocity issues. NMAP2 still crashes when I try to load NVL(old VIL Product), NTP (old total precip product), NMD(mesocyclone product), and the N0S (storm relative velocity product). But everything else seems to be working. TDWR still like what I said before. https://github.com/Unidata/gempak/issues/102#issuecomment-1152995947

Products that still appear to have problems: N.S, NMD, NCR, NVL, NTP and TDWR ref & vel.  Am I missing anything @sebenste?

**Comment by sebenste** [comment]
> > Yes that took care of the reflectivity and velocity issues. NMAP2 still crashes when I try to load NVL(old VIL Product), NTP (old total precip product), NMD(mesocyclone product), and the N0S (storm relative velocity product). But everything else seems to be working. TDWR still like what I said before. [#102 (comment)](https://github.com/Unidata/gempak/issues/102#issuecomment-1152995947)
> 
> Products that still appear to have problems: N.S, NMD, NCR, NVL, NTP and TDWR ref & vel. Am I missing anything @sebenste?

NOS, but I think that's a typo for "N.S" above...

**Comment by mzuranski** [comment]
> NOS, but I think that's a typo for "N.S" above...

I'm using N.S shorthand to encapsulate all tilts.  For this issue if one tilt is affected all would be, so for example if another report comes in of N1S not working, that's already part of the discussion.  :)

**Comment by sebenste** [comment]
> > NOS, but I think that's a typo for "N.S" above...
> 
> I'm using N.S shorthand to encapsulate all tilts. For this issue if one tilt is affected all would be, so for example if another report comes in of N1S not working, that's already part of the discussion. :)

Gotcha!

**Comment by sebenste** [comment]
Have the missing ones been added back?

**Comment by mzuranski** [comment]
After re-reading Kevin's comments and going through [gempak/tables/sat/imgtyp.tbl](https://github.com/Unidata/gempak/blob/main/gempak/tables/sat/imgtyp.tbl) and this PR's changes, I'm starting to wonder if this is an unrelated issue to the imgtyp.tbl changes.

Using NMD as an example, according to [these docs](https://www.weather.gov/media/tg/rpccds_radar_products.pdf), NMD is indeed 141 and listed as Mesocyclone (detection algorithm I'm pretty sure).  And then I see the following lines in imgtyp.tbl:

```
!------------------------------------------------------------------------------
!
! SATELLITE IMAGE TYPES
! ---------------------
!                   |IMG     |      |      |SAT ID|IMGTYP| PIXEL| DEFAULT      |
!SAT ID             |TYP     |   MIN|   MAX|NUMBER|NUMBER| DEPTH| LUT FILE     |
!(20)               |(8)     |   (6)|   (6)|   (6)|   (6)|   (6)|      (14)    |
!                   |        |      |      |      |      |      |              |
!------------------------------------------------------------------------------
NATIONAL  4 KM  BASE REFLECT       0     15      8    141      1 osf_ref16.tbl
REGIONAL  4 KM  BASE REFLECT       0     15      9    141      1 osf_ref16.tbl
```

Those lines have been there for ages, so if NMD stopped working after this PR I'm confused as to how/why; that product hasn't changed.

Kevin notes the symptoms for these other products are different than they were for the N.B and N.G products: https://github.com/Unidata/gempak/pull/103#issuecomment-1152985256  For the moment I'll assume issues for N.S, NMD, NCR, NVL, NTP and TDWR ref & vel are related to each other (i.e. common cause), but that may not be the case either.  Head scratching continues.

I'm going to reach out to Kevin and see if he can send me his table and some sample data that's breaking NMAP2.  If I can recreate the issue hopefully I can sniff out some more breadcrumbs.

**Comment by sebenste** [comment]
Sounds good, Mike!

**Comment by mzuranski** [comment]
> @mzuranski Doesn't the "SAT ID" number matter here such that the RADAR data needs to be `7`?

That's a good question, I'm not sure.  That'll be something I'll test as well.

Kevin got back to me that he's a little busy and will get me sample data and more details on the issue soon.

**Pull request merged**
